### ISSUE TITLE
Azure Blob or AWS S3 Persistence

### ISSUE THREAD

**Issue by gblmarquez** [NEventStore/NEventStore#123]
Hi,

I was thinking on how could be implemented a persistence using a cloud storage or even a file system.

How could be managed the search of commit by date or commit by stream revision?
A simple alternative could be Lucene as an index to search need, what do you think?

There are any simpler alternative to index commits on a storage?

Thanks and regards

Gabriel

**Comment by Breederveld** [comment]
Did anyone get anywhere with either an Azure Blob or Azure Table storage implementation?
If you did try, but failed, can you let us know what was the impeding factor?

I am very much considering doing the implementation myself, but would rather not spend the time to find out it is not possible with the current architecture or if there is a good option already available.
