### ISSUE TITLE
Paged queries are slow for large datasets

### ISSUE THREAD

**Issue by CoreyKaylor** [NEventStore/NEventStore#230]
The queries are always starting with a base row of 0. Here is one example where this happens, but it's not the only place assuming 0 as the starting index. Things seem to work fine until you get into very large datasets.

https://github.com/NEventStore/NEventStore/blob/master/src/NEventStore/Persistence/SqlPersistence/SqlDialects/CommonDbStatement.cs#L129

**Comment by kblooie** [comment]
This issue was moved to NEventStore/NEventStore.Persistence.SQL#8
