### ISSUE TITLE
Prevent writing to > 1 stream in a transaction

### ISSUE THREAD

**Issue by damianh** [NEventStore/NEventStore#287]
The (original) design purpose of stream is to represent an Aggregate Root and this is the **consistency boundary**. Writing to >1 stream in a transaction breaks this and is not an officially supported scenario. Besides, not all persistence engines support .net transactions, let alone 'distributed' transactions (DTC). 

They purpose of the transaction support was really to allow a user to interact with another piece of infrastructure transactionally, i.e. read from a queue or post to an NServiceBus endpoint.

When a user tries to update more than one stream in a single transaction, we should throw.

Some people like to run with scissors, so I am open to allowing an override to prevent the exception from being thrown that must be explicitly set during wireup. Anyone doing this does so at their own risk and without support.

**Comment by RyanBuzzInteractive** [comment]
I guess this change didn't actually happen and probably won't now that the project is pretty static but as a talking point, I think I might have a valid use case for writing to more than one stream in a transaction and would value any comments. 

I am building a mobile application which will work offline and sync with an EventStore server when it reconnects. To do this I am storing all of the pending commands as well as events, so after pulling new data I can re-run the local behaviour and resolve any conflicts.

The best way I could see to do this was to use the NES buckets to partition my store into pending commands, pending events and pulled events. This is my first go at event sourcing so I may be off the mark somewhat.

This approach means I often need to write to multiple partitions for the _same aggregate_.

For instance when a batch of pending events are generated, I store them and their associated command using the same stream ID but in separate buckets, and I want this to be transactional.

I also keep an additional partition ('combined') which has all of the pulled and pending events in one place. I intend to use it for my projections as it provides one checkpointed set of commits.

This needs to be appended whenever a new pending event is commited, and also has to be completely rebuilt after a merge by iterating over both the pulled and pending partitions. This rebuild should also be transactional, but it has to write to _every_ aggregate in the combined stream.

Finally, as part of the above merge processes I need to delete / recreate entire streams in the pending or combined partitions. As (understandably) you can't remove events from an opened stream, I have to use the Advanced.DeleteStream method and then recreate the stream afterwards. Again, if the create fails I want the delete to be rolled back.

Does any/all of this seem like a viable plan? I totally get that committing to multiple aggregates in a transaction shows that you probably have an opportunity to improve your model, but I am being careful not to do that other than in the rebuild case.

**Comment by AGiorgetti** [comment]
Transaction support has been overhauled in the current NEventStore 6.1 and NEventStore.Persistence.Sql 7.x.

A TransactionScope with TransactionScopeOption.Suppress that surrounds any operation will not be created by default anymore (you need to enable the old behavior explicitly calling a configuration function: take a look at the changelogs).

The only behavior left for Microsoft SQL server is: if there's no active transaction (no TransactionScope already created by the user) a privare SQL transaction with ReadCommitted will be created for each operation.

With the new persistence provider the transaction management is totally up to the user.

Some tests were added to show supported and unsupported scenarios (take a look the Microsoft Sql Server persistence tests).

The old behavior can be enabled during NEventStore configuration.

**Comment by RyanBuzzInteractive** [comment]
Hello, thanks for that info.

I previously gathered from the docs that I needed to call the 'EnlistInAmbientTransaction' wireup, and then surround my NEventStore access with a using block which is scoped around a new Transaction. That transaction needs to be manually configured as Required scope and with ReadConfigured isolation / max timeout options.

I am using Sqlite on a mobile device.

This should be all I need to do shouldn't it?

I was also interested in comments on whether these are valid uses case for multi-stream transactions (same aggregate, many partitions etc) .

Cheers!

**Comment by AGiorgetti** [comment]
Writing to multiple streams in a transaction is still a: "do it at your own risk" scenario.

All you need to do with the new default is:

1- open a transaction scope
2- write to as many streams you want
3- complete the scope (or dispose it)

Be careful if you write from multiple threads or if DTC kicks in (because you are mixing writes from multiple connections), it might or might not work depending on many factors.

**Comment by RyanBuzzInteractive** [comment]
I have all my writes queued up on a single thread using an F# mailbox processor so they can't tread on each others toes, that has always worked well for me.

Are you saying that you no longer need to do the ambient transaction wireup, don't need to set the transaction's scope to Required or it's IsolationLevel to ReadConfigured? This is all unnecessary now? I literally just need to create a vanilla transaction scope?

**Comment by RyanBuzzInteractive** [comment]
Just to clarify, it is F# but this is how I am using the connection (the command is a func that takes an event store connection and uses it for whatever access it needs):

```f#
let writeConnectionManager(eventStore : IStoreEvents) =
        MailboxProcessor<EventStoreCommandMessage>.Start (fun inbox ->
            
            let getTxScope () = 
                let mutable txOptions = new TransactionOptions()
                txOptions.IsolationLevel <- IsolationLevel.ReadCommitted
                txOptions.Timeout <- TransactionManager.MaximumTimeout
                new TransactionScope(TransactionScopeOption.Required, txOptions) 
            
            let rec innerLoop dbPath = async {

                let! (command, replyChannel) = inbox.Receive()

                use tx = getTxScope()
                let result = eventStore |> command
                tx.Complete()

                replyChannel.Reply result
                    
                do! innerLoop dbPath
            }
            innerLoop eventStore)

```

**Comment by bartelink** [comment]
If you're in F# land, you might be interested in peeking at https://github.com/jet/propulsion - in there, the general pattern I use is to read in batches and then concurrently+idempotently process the inputs. As progress is achieved, checkpoints gets stored in the checkpoint store. The [missing bit is that there's no way to store state in ES implemented](https://github.com/jet/propulsion/issues/8)

While its unlikely to be directly useful for you, the point for me is that tying stuff together with transactions is just a big dead end IME - instead operating idempotently where any give request can be retries safely will give better throughput, resilience and understandability without leaning on transactions. Of course this does imply more eventual consistency that one might argue/feel/hope for when reaching for transactions as your hammer.

(Dont want to hijack this thread; if interested in to/fro regarding the lib or the concepts, I'm on vacation but drop into the DDD-CQRS-ES slack's #equinox channel evenings). Also for talking through these sorts of architectural concepts, the DDD-CQRS-ES lib can be very useful.

A final point re MBP - in general, my experience is that stuffing things into an Agent queue is unbounded and hard to troubleshoot. While it all 'just actors', the approach of idempotently reacting on a more pull basis and hence having intrinsic backpressure pretty much rules out agents (tough propulsion can be viewed as employing a chain of cooperating agents too)

**Comment by RyanBuzzInteractive** [comment]
Hey man, thanks for that and I will check out the links :)

In my case, the reason I am trying to use transactions is to write one aggregate across multiple partitions (as detailed earlier), and also to ensure that deletes are rolled back if a subsequent create fails when replacing streams, both of which are I guess quite unusual.

It is because the mobile NEventStore instance isn't my source of truth, the EventStore server is, so it needs to be partitioned / merged and also re-written often.

I heed your warning about the mailbox processor, but I think as the NES connection is running locally on the device, serving one user, the queue shouldn't get too long as the writes will be very low impact. I wouldn't consider doing this on a server that is on a network etc.

Anyway, you have given me some stuff to chew on, thanks!

**Comment by AGiorgetti** [comment]
@RyanBuzzInteractive the code you posted should work, as long as anything that happens inside "command" is single threaded.
You can however write a test to confirm the scenario works for you; it if does not, file an issue with the failing test in the NEventStore.Persistence.SQL project.

**Comment by RyanBuzzInteractive** [comment]
Thanks :) I'm still not clear though, are you saying all of that set up on the Transaction object is or isn't necessary? You seemed to imply it was unnecessary earlier.

**Comment by AGiorgetti** [comment]
It is still necessary, also if you plan to use async/await you'll need to add TransactionScopeAsyncFlowOption.Enabled to the mix too.

**Comment by RyanBuzzInteractive** [comment]
Ok cool, thanks for the clarification :)

**Comment by AGiorgetti** [comment]
This whole discussion is actually related to the transaction support in the NEventStore.Persistence.XXX implementations (specifically the SQL one).

With the new Version 7x the defaults were changed: NEventStore now do not creates or suppress new transactions anymore, everything is left to the user.

**Writing to more that one stream per transaction is still an officially unsupported scenario: do it at your own risk because you know what you are doing!**.

You can revert to the old NEventStore behavior when configuring the store itself (see the changelogs and release notes).

I'm going to close this thread, feel free to reopen it if new considerations arise.

**Comment by gaevoy** [comment]
I experimented a bit to took `NEventStore` in the role of [transactional outbox](https://microservices.io/patterns/data/transactional-outbox.html) and it turned out working well https://gaevoy.com/2021/03/18/audit-log-via-transactional-outbox.html

It is a good excuse of using transaction? 😃
