### ISSUE TITLE
reduce log levels

### ISSUE THREAD

**Issue by adamralph** [NEventStore/NEventStore#289]
As discussed with @damianh at JabbR, in some cases current logging seems a bit like stuff that would normally go into 'trace' is going into 'debug' and stuff that would normally go into 'debug' is going into 'info'. E.g.

For a single persistence action at 'info' level:

> NEventStore.OptimisticEventStore                     INFO: Creating stream 'fa0f2312-a752-e311-93ad-082e5f2d2db5'.
> NEventStore.OptimisticEventStore                     INFO: Committing attempt '1ca7a6a6-75fa-422b-bb0d-ab4105de0d62' which contains 2 events to the underlying persistence engine.
> NEventStore.Dispatcher.SynchronousDispatchScheduler  INFO: Scheduling commit '1ca7a6a6-75fa-422b-bb0d-ab4105de0d62' to be dispatched.
> NEventStore.Dispatcher.SynchronousDispatchScheduler  INFO: Marking commit '1ca7a6a6-75fa-422b-bb0d-ab4105de0d62' as dispatched.

For a single persistence action at 'debug' level:

> NEventStore.OptimisticEventStore                                              INFO: Creating stream 'eb616d1b-a752-e311-93ad-082e5f2d2db5'.
> NEventStore.OptimisticEventStream                                            DEBUG: Appending uncommitted event to stream 'eb616d1b-a752-e311-93ad-082e5f2d2db5'
> NEventStore.OptimisticEventStream                                            DEBUG: Appending uncommitted event to stream 'eb616d1b-a752-e311-93ad-082e5f2d2db5'
> NEventStore.OptimisticEventStream                                            DEBUG: Attempting to commit all changes on stream 'eb616d1b-a752-e311-93ad-082e5f2d2db5' to the underlying store.
> NEventStore.OptimisticEventStream                                            DEBUG: Building a commit attempt '224b4a26-1b71-46ef-948d-3d5226ac42f0' on stream 'eb616d1b-a752-e311-93ad-082e5f2d2db5'.
> NEventStore.OptimisticEventStream                                            DEBUG: Pushing attempt '224b4a26-1b71-46ef-948d-3d5226ac42f0' on stream 'eb616d1b-a752-e311-93ad-082e5f2d2db5' to the underlying store.
> NEventStore.OptimisticEventStore                                             DEBUG: Pushing commit '224b4a26-1b71-46ef-948d-3d5226ac42f0' to pre-commit hook of type 'NEventStore.DispatchSchedulerPipelineHook'.
> NEventStore.OptimisticEventStore                                             DEBUG: Pushing commit '224b4a26-1b71-46ef-948d-3d5226ac42f0' to pre-commit hook of type 'NEventStore.Conversion.EventUpconverterPipelineHook'.
> NEventStore.OptimisticEventStore                                              INFO: Committing attempt '224b4a26-1b71-46ef-948d-3d5226ac42f0' which contains 2 events to the underlying persistence engine.
> NEventStore.Persistence.SqlPersistence.SqlPersistenceEngine                  DEBUG: Attempting to commit 2 events on stream 'eb616d1b-a752-e311-93ad-082e5f2d2db5' at sequence 1.
> NEventStore.Persistence.SqlServerPersistence.SqlDialects.SqlServerStatement  DEBUG: Adding parameter named '@StreamId' to statement.
> NEventStore.Persistence.SqlServerPersistence.SqlDialects.SqlServerStatement  DEBUG: Adding parameter named '@StreamRevision' to statement.
> NEventStore.Persistence.SqlServerPersistence.SqlDialects.SqlServerStatement  DEBUG: Adding parameter named '@Items' to statement.
> NEventStore.Persistence.SqlServerPersistence.SqlDialects.SqlServerStatement  DEBUG: Adding parameter named '@CommitId' to statement.
> NEventStore.Persistence.SqlServerPersistence.SqlDialects.SqlServerStatement  DEBUG: Adding parameter named '@CommitSequence' to statement.
> NEventStore.Persistence.SqlServerPersistence.SqlDialects.SqlServerStatement  DEBUG: Adding parameter named '@CommitStamp' to statement.
> NEventStore.Persistence.SqlServerPersistence.SqlDialects.SqlServerStatement  DEBUG: Adding parameter named '@Headers' to statement.
> NEventStore.Persistence.SqlServerPersistence.SqlDialects.SqlServerStatement  DEBUG: Adding parameter named '@Payload' to statement.
> NEventStore.Persistence.SqlPersistence.SqlPersistenceEngine                  DEBUG: Commit '224b4a26-1b71-46ef-948d-3d5226ac42f0' persisted successfully.
> NEventStore.OptimisticEventStore                                             DEBUG: Pushing commit '224b4a26-1b71-46ef-948d-3d5226ac42f0' to post-commit hook of type 'NEventStore.DispatchSchedulerPipelineHook'.
> NEventStore.Dispatcher.SynchronousDispatchScheduler                           INFO: Scheduling commit '224b4a26-1b71-46ef-948d-3d5226ac42f0' to be dispatched.
> NEventStore.Dispatcher.SynchronousDispatchScheduler                           INFO: Marking commit '224b4a26-1b71-46ef-948d-3d5226ac42f0' as dispatched.

I think most of the 'debug' stuff should be at 'trace' level and most of the 'info' should be at 'debug' level.

**Comment by alkampfergit** [comment]
I've started a new feature branch, in this branch I've started doing some improvement to log interface.

1. I've added IsDebugEnabled, IsVerboseEnabled IsInfoEnabled to the base Logger
1. We have now a base implementation for logger that allows you to choose log level
1. Added lots of info to track all the initialization
1. Moved a lot of the Debug calls to Verbose calls.

This is the output for the sample application when level is set to Info

![image](https://cloud.githubusercontent.com/assets/358545/16811092/1168d562-4927-11e6-8567-8bc519c22009.png)

If you raise log to Debug I've left only very few of the call, all the other were moved to verbose. I accept suggestion on what do you expect to see at Debug level.

![image](https://cloud.githubusercontent.com/assets/358545/16811118/313d79a6-4927-11e6-8f11-89828032ff6b.png)
