### ISSUE TITLE
Event with an empty body doesn't get commited

### ISSUE THREAD

**Issue by MaximRouiller** [NEventStore/NEventStore#356]
So I have an object that is an EventMessage defined as this:

    public class MeetingScheduled : EventMessage
    {
        public string MeetingName { get; set; }
    }

And when I try to add it like so: 

    using (var stream = store.CreateStream(StreamId))
            {
                stream.Add(new MeetingScheduled() { MeetingName = "Test meeting"});
                stream.CommitChanges(Guid.NewGuid());
            }

The event gets processed but never reach storage. No exceptions were thrown. Nothing in the Debug output window (even if I have LogToOutputWindow() invoked).

Literally wasted hours on this issue. The best would be an exception at the moment of adding the event. The good would be to inform me through the output/console window. The ugly would be to just swallow the event and not informing me that it was never processed.

Maybe a better example project would help too. 

Please discuss, request help, throw me rocks (I'll building something out of it).

**Comment by AGiorgetti** [comment]
The point here is that you should not extend EventMessage, this class is going to be sealed in the next version. If you need to add these bits of information should go in the Header property of the EventMessage class.

We will add an "InvalidCommitAttemptException" or something similar if you try to persist an EventMessage without a body.
