### ISSUE TITLE
Race condition in sync and async dispatchers can result in subscribers getting commits / events out of order

### ISSUE THREAD

**Issue by damianh** [NEventStore/NEventStore#360]
If a stream (AR) is updated in very rapid _succession_  on separate threads (http requests) there is a window of opportunity for the commits/events to be dispatched out-of-order. It's a very small window but stil,l a subscriber must be guaranteed that the order they receive commits / events in is the stream order.

These are the scenarios that may occur:
![image](https://cloud.githubusercontent.com/assets/57436/3902865/8edcac20-22c4-11e4-8ce8-936984a3c7cb.png)

![image](https://cloud.githubusercontent.com/assets/57436/3902877/a6a1d7b8-22c4-11e4-8c32-614504110a5e.png)

![image](https://cloud.githubusercontent.com/assets/57436/3902884/bcadd070-22c4-11e4-9910-56637c0e8a54.png)

Here, scenarios 1 & 2 result in desired behavior, but scenario 3 _may_ occur. That one time. In production.

The only way to guarantee the order is to read form the store seperately, thus this whole dispatching stuff needs to be ripped out.

**Comment by 9swampy** [comment]
In case it helps anyone dealing with the consequences of this issue I've incorporated @larsw suggestion above into https://github.com/9swampy/NEventStoreExample/commit/6fb85668f98bf7556a77ef7dbd8be51414b933c2
