### ISSUE TITLE
Remove xunit customer runner from tests, come up with a similar way to do the BDD style tests.

### ISSUE THREAD

**Issue by damianh** [NEventStore/NEventStore#371]
Custom runner doesn't work in ncrunch and the whole API has change in xunit 2.0

**Comment by larsw** [comment]
What about just using machine.specifications?

**Comment by andreabalducci** [comment]
+1 all our bdd test on top of NES & our products are based on mspec, we are very satisfied.

**Comment by kblooie** [comment]
This project was actually using mspec and we moved away from it. The custom BDD code for XUnit was added to make it as close to the existing mspec tests as possible to simplify moving away from it. 

I've used mspec for a while. The primary issue is that it's too easy to mess up and have hard to read buggy tests. You initialize one static field outside of a context and a group of tests fail... sometimes... 

Also, in every project I've used it, there's been a ton of friction with on-boarding new devs. It's a unique way of writing tests that's not easy to understand at first.

I say we stick w/ XUnit and find a non-custom approach to BDD.

**Comment by andreabalducci** [comment]
maybe was a bug on the previous versions, we have 700+ mspec tests on our current project without any issue.

**Comment by andreabalducci** [comment]
@kblooie we need to run the persistence tests with different options for a given provider (eg: mongo with or without server side checkpoint), there's a simple way to do this with current test framework?

**Comment by AGiorgetti** [comment]
Changed how testing works: created some support classes so we can chose between XUnit, NUnit or MSTests.
Actually NUnit is configured via build constants in csproj files.
