### ISSUE TITLE
DuplicateCommitException needs more information

### ISSUE THREAD

**Issue by thefringeninja** [NEventStore/NEventStore#372]
e.g. which expected version the stream was at

**Comment by AGiorgetti** [comment]
The excpetion fires when there's an attempt to have two commits with the same CommitId in the stream.

The information it can report might be very specific to each Persistence implementation.

We can however add more information to the exception message.

**Comment by AGiorgetti** [comment]
Improved the error message in NEventStore.Persistence.MongoDB

**Comment by AGiorgetti** [comment]
Improved error messages on:
NEventStore.Persistence.SQL
NEventStore.Persistence.MongoDB
