### ISSUE TITLE
Ambient transaction regression in 5.1.0

### ISSUE THREAD

**Issue by adamralph** [NEventStore/NEventStore#373]
After moving from 5.0.1.2 to 5.1.0, an SQL exception was raised with the following message*

> The COMMIT TRANSACTION request has no corresponding BEGIN TRANSACTION.

Thanks to @hyrmn, I discovered that exception can be avoided by removing `.EnlistInAmbientTransaction()` from the wire up.

So questions remaining are:

1. What effect does removing that have?
1. Does this need fixing?

\* *Unfortunately I can't copy and paste the stacktrace because my place of work have banned writing to GitHub and I can't think of a legal way of sending it outside the company.*

**Comment by damianh** [comment]
> implement  transactional updates of a message queue and an event store using NEventStore (i.e., transactional, push-based event bus)

This was the original intention but wouldn't handling such messages idempotenty be a superior approach? Also, this is leaky in that it only works for a subset of storage engines. 

> can implement transactionally updated synchronous read models if your application needs them.

This scenario is actually horribly broken, see #360

**Comment by fschmied** [comment]
>> implement transactional updates of a message queue and an event store using NEventStore (i.e., transactional, push-based event bus)

> wouldn't handling such messages idempotenty be a superior approach?

For many applications, definitely. For other applications, this architecture could be the simplest thing that works and thus exactly what they need.

>> can implement transactionally updated synchronous read models if your application needs them.

> This scenario is actually horribly broken, see #360 

You don't need to use synchronous dispatchers for that. What I meant is that you can do this (at least in 3.1.0 and later):

    using (var tx = new TransactionScope())
    {
      _transactionallyEnabledEventStoreRepository.Save();
      _somethingElse.Update(); // could be read models, message bus, whatever

      tx.Commit();
    }

I don't say this is best practice or absolutely required - you can always work around in some way -, but it's nice. It's not always about DTC, either. I myself have used this approach to store metadata about imported events (pulled from another event store) transactionally within the event store DB. Removing that feature would have required me to deal with scenarios where events have no metadata or metadata has no events - that would just have increased complexity with no benefit for me. IMO, that's the special thing about frameworks and libraries - your users sometimes use them in a way you didn't anticipate. However, that does not render those use cases obsolete.

> Also, this is leaky in that it only works for a subset of storage engines.

That's probably why it is turned off by default. However, look at it this way. You are a developer that explicitly wants to use a SQL Server-based event store. NEventStore is currently _the_ way to go (IMO), so you choose to use it. SQL Server has a feature allowing it to enlist in ambient transactions that you want to make use of. You discover that NEventStore disables that feature. (For, me, BTW, this would be a big WTF moment.) Luckily, you discover `EnlistInAmbientTransaction()`.

In my opinion, this is a very valid case (probably the only caste) where you want to re-enable the ambient transaction enlistment. And it's good that you can.

What are your reasons for wanting to remove it? (And people calling an API without knowing why or what it does is _not_ a good reason, IMO.)

**Comment by damianh** [comment]
Good points.

My only counter argument is that it does not help the user fall into the
pit of success. For example it allows updating of more than one stream in a
transaction breaking the whole concept of stream based consistency
boundaries. Throw in a synchronsous dispatcher (which is horribly broken in
its own way) and any projections then fall under the same transaction scope.

Any suggestions on mitigating this? Prevent updating of more than one
stream in a transaction perhap? (The dispatcher stuff will be removed)

**Comment by fschmied** [comment]
@damianh If the reason is only because of async/await, just use the `TransactionScopeAsyncFlowOption.Enabled` parameter when constructing the scope.

**Comment by fschmied** [comment]
@damianh I think the pit of success is there anyway because of the sensible default (from the point of most users).

I see `EnlistInAmbientTransaction` as a "I know what I'm doing" feature anyway. So if someone **wants** to commit two streams in the same DB transaction by opting in (i.e., using `EnlistInAmbientTransaction` + creating a larget TransactionScope), so be it. Or am I missing something that would break horribly if NES were used that way?

**Comment by adamralph** [comment]
What's the latest on this? I was upgrading NuGet packages in a project just now and my mouse hovered dangerously over NES 5.1 before I remembered about this bug.

As a gentle reminder - this breaks people upgrading from <5.1 to 5.1. At the moment I'm still having to remember not to upgrade from 5.0.x to 5.1 to prevent breaking my applications.

**Comment by fschmied** [comment]
@adamralph Didn't you say you don't need `EnlistInAmbientTransaction` anyway? So why not remove the call and then upgrade to NES 5.1?

**Comment by adamralph** [comment]
I discovered that removing it got rid of the error, but the primary reason I raised this issue was to find out what effect that has. The conversation since then has answered that in a roundabout way, since I know have some understanding of what this method was originally designed to do. Later (https://github.com/NEventStore/NEventStore/issues/373#issuecomment-64386347) I specifically asked whether I could safely remove it but I never got an answer.

Anyway, I get the feeling that I can safely remove it so I guess I'll just go ahead and do that.

The secondary reason for raising this issue was to improve the experience for anyone else who is surprised when then they upgrade to 5.1.0 and their application breaks. IMO the method either needs to be fixed or obsoleted to a no-op.

**Comment by adamralph** [comment]
I guess anything other than fixing the method necessitate a major version bump, since any application relying on transactions will break. So unless 5.1 can be patched to fix it, it should probably be unlisted.

**Comment by fschmied** [comment]
Sure needs to be fixed, I just meant that it should probably not be a blocker for your update if you don't need the broken API anyway.

A good indication of whether you need it is probably whether you open up any TransactionScopes (around calls into NES).

**Comment by damianh** [comment]
Agree that anything other than fixing it would require a major version bump.
>
>

**Comment by damianh** [comment]
Finally tracked it down to this change https://github.com/NEventStore/NEventStore/commit/21ada5290bf3c0376f57ce596677259d52fb8d3b which is related to issue #343

**Comment by damianh** [comment]
It only happens if there is an existing `Commits` table.

**Comment by adamralph** [comment]
Aha, well done for finding that!
