### ISSUE TITLE
SqlPersistenceEngine.GetCheckpoint(null) should not return null

### ISSUE THREAD

**Issue by damianh** [NEventStore/NEventStore#374]
https://github.com/NEventStore/NEventStore/blob/master/src/NEventStore/Persistence/Sql/SqlPersistenceEngine.cs#L136

This should just call LongCheckpoint.Parse() that will deal with null checkpoint tokens.

**Comment by larsw** [comment]
Is there anything else than fixing the line in question to close this bug (e.g. should there be added a test)?
