### ISSUE TITLE
Aggr.Save() to return Success/Fail Info

### ISSUE THREAD

**Issue by danielHalan** [NEventStore/NEventStore#375]
Hi, 

It would be nice if EventStoreRepository.Save() returned information of the Transaction, if Successful or Failed, and if failed how (DuplicateCommit, Concurrency etc). so approariate actions can be made if necessary.

**Comment by damianh** [comment]
Not sure I get you here. A Save() is expected to just work, it doesn't need to return anything. If something goes wrong, then an exception of some sort will be thrown.

Or am I misunderstanding you?

**Comment by danielHalan** [comment]
Yes, but as Save can still be successful without persisting anything, a return value would be indicated if anything got persisted, and if not, why...

**Comment by warappa** [comment]
A thought regarding Save():
Maybe the current `CheckpointNumber` could be returned

No CheckpointNumber, nothing saved.
Read as "If no CheckpointNumber is returned: nothing has changed in the eventstore" - I'm personally fine having exceptions if events > 0 were not saved.

An possible (bad?) use-case:
The application (like the Asp.NET server side) should wait for the completion of an async read-model-projection of a specific command (I call it `SendAndWait`). If we had the checkpoint-number we could include this in our projection. The command-side would have the option to wait for the checkpoint to appear in the read-model and just after *that* getting back to the client implying "data is ready".

**Comment by damianh** [comment]
Interesting idea, let me chew on this..

**Comment by andreabalducci** [comment]
@warappa you can do it with a pipeline hook. On the PostCommit you have the checkpoint id.
