### ISSUE TITLE
EventStoreRepository does not return correct aggregate versions

### ISSUE THREAD

**Issue by trailmax** [NEventStore/NEventStore#376]
If I get 2 different revisions of the same aggregate from `EventStoreRepository`, on the second method execution, I get incorrect version - copy of aggregate requested in the first method.

Here are the failing tests: https://gist.github.com/trailmax/7c97ac7bdfa68c8613e0

Basically it all goes like this

    var aggregateV1 = repository.GetById<MyAggregate>(id, 1);
    var aggregateV2 = repository.GetById<MyAggregate>(id, 2);

the second line returns revision 1, does not even go into rev2.

**Comment by AGiorgetti** [comment]
Moved to:
https://github.com/NEventStore/NEventStore.Domain/issues/6
