### ISSUE TITLE
Saga

### ISSUE THREAD

**Issue by adamfur** [NEventStore/NEventStore#385]
Hi, Curious to know if the Saga implementation is correct.

A sage listens to events, ISaga.Transition() receives the event, the event is then routed to the appropriate method.

When the Saga is presisted, it's supposed to dispatch undispatched messages. However it seems to dispatch the received events! Causing a loop and resulting in a Concurreny Exception.

**Comment by larsw** [comment]
Hi,

Are you sure you're not mixing up Transition() and Dispatch()?

https://github.com/NEventStore/NEventStore/blob/master/src/NEventStore/CommonDomain/Core/SagaBase.cs

Transition() adds messages to the uncommited list, Dispatch() adds messages to the undispatched list.

**Comment by adamfur** [comment]
Hi,

From: http://blog.jonathanoliver.com/cqrs-sagas-with-event-sourcing-part-ii-of-ii/

public void Handle(OrderReceivedEvent message)
{
    var sagaId = message.OrderId; // purchase correlation
    var saga = repository.GetById(sagaId);
    saga.Transition(message);
    repository.Save(saga);
}

In this case, an aggregate has triggered the OrderReceivedEvent and the Saga is about to respond to this event.
The message is routed to the appropriates method in the Saga via the Transition() method, the method in question will create a command and use Dispatch() so the framework can dispatch as I like, once the sage is persisted.

From my experience today, the Transition()ed events, are put back in the bus (infinite loop). And the Dispatch()ed commands are just ignored.

Am I doing this incorrectly, or is the Saga currently in a bad state?

**Comment by adamfur** [comment]
Think I might have figured it out.
I'm using a class derived from IPipelineHook to dispatch all the events to a bus.
If the commit contains headers that starts with "UndispatchedMessage." I have to grab the command from there and dispatch it instead of the events?

**Comment by adamfur** [comment]
Saga in latest NuGet is broken, Saga was fixed in commit 1021f9b005563f3bee74e68388a88b19285baff7

**Comment by damianh** [comment]
there will be an updated package shortly

**Comment by adamfur** [comment]
NuGet for version 5.1.1 contains fix. Thank you
