### ISSUE TITLE
NEventStore Tables in custom schema

### ISSUE THREAD

**Issue by jskrepnek** [NEventStore/NEventStore#386]
Hi,

I'm working with a DB requirement (Oracle) that tables be owned by a user ("schema") that is different from the user that accesses those tables.  I'm trying to understand how, if possible, to support this with NEventStore and/or Oracle.

For example:

Given a user APPLICATION
and a schema EVENTSTORE

The commits table would need to be 'owned' by EVENTSTORE; i.e.: EVENTSTORE.COMMITS.  

Then the user APPLICATION would be granted the necessary privileges to access EVENTSTORE.COMMITS.  

However, the APPLICATION user accesses the Commits table implicitly; i.e.: SELECT * FROM COMMITS.  As far as I know, the Commits table would be assumed to be owned by the APPLICATION user.

What I need is to be able to have NEventStore explicitly use the owning schema: i.e.: SELECT * FROM EVENTSTORE.COMMITS

I appreciate that this may as much be a problem that we solve outside of NEventStore; so I'm hoping to connect with others that have worked around a similar situation.

Thanks,

Joel

**Comment by damianh** [comment]
I don't know is the short answer. I strongly suspect you'd have to modify all of the [oracle native statements](https://github.com/NEventStore/NEventStore/blob/master/src/NEventStore/Persistence/Sql/SqlDialects/OracleNativeStatements.resx).

**Comment by kblooie** [comment]
This issue was moved to NEventStore/NEventStore.Persistence.SQL#5
