### ISSUE TITLE
Best Practice Stream Data

### ISSUE THREAD

**Issue by Gentlehag** [NEventStore/NEventStore#390]
as the Dispatch method is marked obsolete which is descriped in the linked thread i wonder my self how should i inform subscribers that there are new events ? 

I'd like to get some change eventstream.

How do you do this ?

**Comment by gregoryyoung** [comment]
See the polling consumer
https://github.com/NEventStore/NEventStore/blob/master/src/NEventStore.PollingClientExample/MainProgram.cs#L15

On Thu, Feb 12, 2015 at 7:32 PM, Boas Enkler <notifications@github.com>
wrote:

> as the Dispatch method is marked obsolete which is descriped in the linked
> thread i wonder my self how should i inform subscribers that there are new
> events ?
>
> I'd like to get some change eventstream.
>
> How do you do this ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NEventStore/NEventStore/issues/390>.
>



-- 
Studying for the Turing test

**Comment by larsw** [comment]
What @gregoryyoung said + more background info in this issue https://github.com/NEventStore/NEventStore/issues/360
