### ISSUE TITLE
Speed up replay from SQL Server

### ISSUE THREAD

**Issue by danbarua** [NEventStore/NEventStore#391]
I'm not sure how relevant this is to V5/6 but this massively speeds up replays on MSSQL:

```sql
CREATE NONCLUSTERED INDEX [IX_Commits_Ordered] ON [dbo].[Commits]
(
	[CommitSequence] ASC,
	[StreamId] ASC,
	[StreamRevision] ASC
)
```

**Comment by damianh** [comment]
nice!

**Comment by OyvindAndersen** [comment]
Hi,

On what version did you add this index? We're using both 2.x and 5.x and for 2.x the PK_Commits has StreamId and CommitSequence. This seems for me like a good index but I have not investigated the actual sql statement for replay.

Why wouldn't you want StreamId first and then CommitSequence. Does including StreamRevision increase performance?

Have you tried snapshots if your performance regarding replays are slow?

**Comment by danbarua** [comment]
This was on V3/4. Snapshots are no use when rebuilding my read model as it needs all the events regardless.
My read model rebuild code is essentially this:
```csharp
foreach(var commit in store.Advanced.GetFrom(DateTime.MinValue)
foreach(var @event in commit.Events)
{
  DispatchToEventHandlers(@event);
}
```
I just found this by playing around with SQL Profiler during replays and looking at the query plans.

**Comment by OyvindAndersen** [comment]
Ahh. Ok. In your case u're using DateTime and the actual sql statement is ordered by CommitStamp, StreamId and StreamRevision, at least for V2. So that should be a good index also. There is already one for CommitStamp (IX_Commits_Stamp) that maybe could include StreamId and StreamRevision so you don't need two indexes.

**Comment by kblooie** [comment]
This issue was moved to NEventStore/NEventStore.Persistence.SQL#4
