### ISSUE TITLE
SqlPersistanceFactory requires an explicit sql dialect when provided an IConnectionFactory

### ISSUE THREAD

**Issue by Jared314** [NEventStore/NEventStore#395]
The `NEventStore.Serialization.SqlPersistanceFactory` constructor that accepts a database connection string name, automatically resolve the sql dialect if non is provided. But, the constructor that accepts an `IConnectionFactory` requires an explicit sql dialect. The `IConnectionFactory` interface contains a method to get the provider type information and could also automatically resolve the dialect.

I currently utilize `IConnectionFactory` to wrap custom database resolution logic, and had to implement custom dialect detection. Is the behavior difference intentional? Should I not be using the `UsingSqlPersistence(IConnectionFactory factory)` overload for wireup?

**Comment by kblooie** [comment]
This issue was moved to NEventStore/NEventStore.Persistence.SQL#3
