### ISSUE TITLE
Get DB connection for bucket/tenant

### ISSUE THREAD

**Issue by di97mni** [NEventStore/NEventStore#397]
Add bucket id to [IConnectionFactory.Open()](https://github.com/NEventStore/NEventStore/blob/master/src/NEventStore/Persistence/Sql/IConnectionFactory.cs#L8) to be able to separate DBs per tenant

In current solution we need to wire up one eventstore per tenant instead of implementing a custom connection factory that can resolve DB per bucket id/tenant

**Comment by kblooie** [comment]
This issue was moved to NEventStore/NEventStore.Persistence.SQL#2
