### ISSUE TITLE
At least in SqlPersistenceEngine, commit stamps are only saving with datetime precision, even though DB field is datetime2

### ISSUE THREAD

**Issue by snissim** [NEventStore/NEventStore#399]
The CommitStamp parameter needs to be added to the command explicitly with DbType.DateTime2.  I will create a PR.

Here's a before and after:

![image](https://cloud.githubusercontent.com/assets/1406142/6678885/63c6d1c0-cc0e-11e4-96c0-bba3a32f9266.png)

**Comment by kblooie** [comment]
This issue was moved to NEventStore/NEventStore.Persistence.SQL#1
