### ISSUE TITLE
Timestamp on events

### ISSUE THREAD

**Issue by srogovtsev** [NEventStore/NEventStore#401]
What I'd like to do: open an event stream and get committed events with timestamp on each event.

And I've found no way to do it. First, I expected some kind of timestamp on each `EventMessage`, but I suppose that was replaced by `ICommit`'s timestamp. Then I tried to find a way to get to `ICommit` from `EventMessage`, but there's none. And finally, there's no way of getting `ICommit`s from event stream.

So, what I have to do is: use `Store.Advanced` and get all commits (instead of commits for specified stream), and then enumerate events in them.

What am I missing?

**Comment by yreynhout** [comment]
What's wrong with adding it to the headers yourself? Or to the payload? Time seems like a pretty important intrinsic attribute to me.

**Comment by srogovtsev** [comment]
Exactly because event timestamp seems an intrinsic event attribute to me, I was surprised not finding it in the `EventMessage`. Of course I can add it manually, but because it is a cross-cutting concern it'd be pretty messy.

**Comment by gregoryyoung** [comment]
I am just curious what would "Event Timestamp" mean?

Is that the time the event was created? The time it hit the library to be
saved? The time it was actually saved?

Also why would it be messy to add a cross cutting concern to an envelope
(metadata) thats what the pattern is supposed to do well.

On Thu, Mar 19, 2015 at 8:14 PM, Serg Rogovtsev <notifications@github.com>
wrote:

> Exactly because event timestamp seems an intrinsic event attribute to me,
> I was surprised not finding it in the EventMessage. Of course I can add
> it manually, but because it is a cross-cutting concern it'd be pretty messy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NEventStore/NEventStore/issues/401#issuecomment-83698247>
> .
>



-- 
Studying for the Turing test

**Comment by srogovtsev** [comment]
I'd prefer event timestamp to be user-defined - e.g., the code that's creating an event would define this timestamp according to business rules (e.g. "time user hit the button"). As far as I understood there's already a "the time it was saved" timestamp in NEventStore - a commit timestamp.

About messiness: basing on the same notion of event timestamp as an user-defined value, I'd have to either create an new class derived from `EventMessage` or add some kind of extension method on `EventMessage` to store it to headers.

Of course, if we leave the value to the library - i.e., setting it at the time of commit or something like that - I suppose there would be some hook that'd allow for that without single line of client code.

**Comment by yreynhout** [comment]
What part of EventMessage.Headers is unclear to you? Just add the metadata you want.

https://github.com/NEventStore/NEventStore/blob/master/src/NEventStore/EventMessage.cs

Verstuurd vanaf mijn iPhone

**Comment by gregoryyoung** [comment]
"About messiness: basing on the same notion of event timestamp as an
user-defined value, I'd have to either create an new class derived from
EventMessage or add some kind of extension method on EventMessage to store
it to headers."

A better question is why are you even using EventMessage many places in
your code? Much of the design has been lifted from GES and I can tell you
we have 0 expectation that you would use our equivalent EventData in your
code except to translate it into something that you actually use. I
actually think EventMessage made the big mistake of giving it back to you
as something that you may be able to use. We give you back things as byte
vectors just to make it more clear this is the intention.

Your use case is exactly why metadata exists. Add a header. Don't use
EventMessage directly (convert it to/from something that makes sense to
you). I am not aware of what CD does with any of this btw

On Thu, Mar 19, 2015 at 8:29 PM, Serg Rogovtsev <notifications@github.com>
wrote:

> I'd prefer event timestamp to be user-defined - e.g., the code that's
> creating an event would define this timestamp according to business rules
> (e.g. "time user hit the button"). As far as I understood there's already a
> "the time it was saved" timestamp in NEventStore - a commit timestamp.
>
> About messiness: basing on the same notion of event timestamp as an
> user-defined value, I'd have to either create an new class derived from
> EventMessage or add some kind of extension method on EventMessage to
> store it to headers.
>
> Of course, if we leave the value to the library - i.e., setting it at the
> time of commit or something like that - I suppose there would be some hook
> that'd allow for that without single line of client code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NEventStore/NEventStore/issues/401#issuecomment-83703865>
> .
>



-- 
Studying for the Turing test

**Comment by srogovtsev** [comment]
@gregoryyoung I am new to event sourcing, and right now I am looking for a suitable implementation for my project. What I have is something like a pipeline with some kind of message passing through, and on each stage of the pipeline I save the audit trail - timestamp, stage, state of message and some stage-dependent data. That was implemented some time ago with RDBMS as a storage, and of course there was a lot of trouble due to schema changes.

When I read about event sourcing I thought that it'd be a perfect fit for this situation, because the trail would be the events themselves, and I could gather any statistics that I want on top of that via dispatching. And I was surprised to see while there is some metadata on event - in NEventStore that's headers, - there's no timestamp although I thought that it's something intrinsic to an event, a moment in time when it happened.

It just seems somewhat unnatural, adding a "Timestamp" property to every event info that I'll put into body, or make a typed wrapper to put it to headers. That's why I asked, if there's some part of system that I miss, or just something that I don't get. (And, by the way, there's something more or less like that, an `ICommitEvent` interface that allow me to see commits, that do have a timestamp, and events for each commit. It's just not on a surface.)

And, as far as I can see, in GES there is a `Created` property, which fits my bill exactly. 

Sorry for somewhat confusing text.

**Comment by gregoryyoung** [comment]
You are misunderstanding me.

Add your own header! Don't put it on every event.

Created in GES is when it was committed in the database. For your own
semantics we would say the same create something in metadata "entered". We
have metadata which is say json (same idea).

As for typed wrappers your code wouldn't be interacting with Headers
directly (2 functions would one from your idea of them to EventMessage, one
the other direction)

Greg

On Thu, Mar 19, 2015 at 10:06 PM, Serg Rogovtsev <notifications@github.com>
wrote:

> @gregoryyoung <https://github.com/gregoryyoung> I am new to event
> sourcing, and right now I am looking for a suitable implementation for my
> project. What I have is something like a pipeline with some kind of message
> passing through, and on each stage of the pipeline I save the audit trail -
> timestamp, stage, state of message and some stage-dependent data. That was
> implemented some time ago with RDBMS as a storage, and of course there was
> a lot of trouble due to schema changes.
>
> When I read about event sourcing I thought that it'd be a perfect fit for
> this situation, because the trail would be the events themselves, and I
> could gather any statistics that I want on top of that via dispatching. And
> I was surprised to see while there is some metadata on event - in
> NEventStore that's headers, - there's no timestamp although I thought that
> it's something intrinsic to an event, a moment in time when it happened.
>
> It just seems somewhat unnatural, adding a "Timestamp" property to every
> event info that I'll put into body, or make a typed wrapper to put it to
> headers. That's why I asked, if there's some part of system that I miss, or
> just something that I don't get. (And, by the way, there's something more
> or less like that, an ICommitEvent interface that allow me to see
> commits, that do have a timestamp, and events for each commit. It's just
> not on a surface.)
>
> And, as far as I can see, in GES there is a Created property, which fits
> my bill exactly.
>
> Sorry for somewhat confusing text.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NEventStore/NEventStore/issues/401#issuecomment-83743206>
> .
>



-- 
Studying for the Turing test

**Comment by srogovtsev** [comment]
I know that `Created` is the time the event was committed to the database. In my own case (not the generic one) that'd be enough. But I agree that if we want to add another one - like `Entered` it'd be better suited for metadata than some data.

At the beginning of the discussion I wondered why NEventStore's `EventMessage` does not have something like GES's `Created`, but I suppose the answer would be "because `ICommit` does".

**Comment by gregoryyoung** [comment]
"At the beginning of the discussion I wondered why NEventStore's
EventMessage does not have something like GES's Created, but I suppose the
answer would be "because ICommit does"."

Yes because to this day for backwards compatibility reasons they have the
"read same transaction you wrote" which is not a very good decision (IIRC
historically it was done for performance) but its hard to change.

On Thu, Mar 19, 2015 at 10:17 PM, Serg Rogovtsev <notifications@github.com>
wrote:

> I know that Created is the time the event was committed to the database.
> In my own case (not the generic one) that'd be enough. But I agree that if
> we want to add another one - like Entered it'd be better suited for
> metadata than some data.
>
> At the beginning of the discussion I wondered why NEventStore's
> EventMessage does not have something like GES's Created, but I suppose
> the answer would be "because ICommit does".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NEventStore/NEventStore/issues/401#issuecomment-83747788>
> .
>



-- 
Studying for the Turing test
