### ISSUE TITLE
Polling only one bucket

### ISSUE THREAD

**Issue by hnafar** [NEventStore/NEventStore#405]
The polling client uses IStoreEvents.Advanced.GetFrom to retrieve events.
IStoreEvents.Advanced.GetFrom has overloads to specify a bucketId when using versions or DateTime to filter out results, but no such overload when using a checkpoint.
Currently I am using MongoDB Persistence, and in order to use a checkpoint, I have to read all events from all buckets, aside from the inherent inefficiency, this also forces me to have to register classmaps for all events in the store, instead of only those from the bucket I am interested in.

Is there any way at all to poll only one bucket while using MongoPersistence?

**Comment by hnafar** [comment]
IPersistStreams.GetFrom(bucketId, checkpointToken) would have been ideal for this.

**Comment by andreabalducci** [comment]
Polling client is persistence agnostic, so this implementation should be done for all the persistence providers. 
@damianh what do you think about this feature?

**Comment by andreabalducci** [comment]
@hnafar planned for next release (as soon as we have the new CI server up & running)

**Comment by hnafar** [comment]
@andreabalducci let me know how I can help.

**Comment by andreabalducci** [comment]
todo: 
mongo
raven.

**Comment by Iridio** [comment]
this week I will update RavenDB
