### ISSUE TITLE
Setup a new build server

### ISSUE THREAD

**Issue by andreabalducci** [NEventStore/NEventStore#406]
TeamCity 9.x
Tests on all supported databases
Tests for pull requests
Integration with GitHub

**Comment by andreabalducci** [comment]
SqlServer up & running
Oracle up & running

**Comment by andreabalducci** [comment]
[x] PostgreSql (5 test failing)

**Comment by alkampfergit** [comment]
[X] Ilmerge and publish on myget.

**Comment by andreabalducci** [comment]
Build server up & running.

**Comment by andreabalducci** [comment]
RavenPersistence assembly is without version number, @alkampfergit we have to check all the builds

**Comment by andreabalducci** [comment]
@kblooie we'll check the new build configuration

**Comment by kblooie** [comment]
Raven & Mongo expect the version number to be given by the build server. It looks like the core project uses a different approach where only the build number is passed to the scripts & the version is stored in VersionAssemblyInfo.cs

Which approach do we want to use across all projects?

**Comment by kblooie** [comment]
I'm pretty sure this is why the assembly doesn't have the right version

**Comment by andreabalducci** [comment]
I know, this is the issue for sure, already checked this afternoon.

**Comment by kblooie** [comment]
I just made pull requests for mongo and raven. The core project also has a
bug where the build number isn't getting set in the assembly. I'll send a
pull request in a bit

**Comment by kblooie** [comment]
@alkampfergit After changing raven persistence to use the same strategy for updating the assembly version, the assemblies still aren't being updated with the build number. How are you passing the build number to the scripts?

**Comment by alkampfergit** [comment]
I'm checking the builds. Actually Raven Build uses the standard Build.RunTask.bat file, while core build is using tasks from TeamCity. Tomorrow I'll speak with Andrea to uniform all the build, in the meanwhile I've fixed the build for RavenDb persistence plugin, passing the number of the build. If you get package generated by the build 21 (https://www.myget.org/feed/neventstore-ci/package/nuget/NEventStore.Persistence.RavenDB) you should see the build number in the FileInformationalVersion

![image](https://cloud.githubusercontent.com/assets/358545/7786909/050c6a5a-01ec-11e5-8f3c-df3b2d395ded.png)

**Comment by alkampfergit** [comment]
Added call to Build.runTask.Bat in base build to call psake target UpdateVersion in the build for the Core project.

Now we need to check versioning for MongDb and create build for the SQL persistence that is now moved in separate repository.

**Comment by kblooie** [comment]
For nuget versioning, what do we gain by having a version number structure of "5.2.0-build21-pre". Does this help with sorting or something? 

This makes it harder to deploy a stable build that matches the assembly version. Using "5.2.0.21-pre" makes it to where we can simply remove the pre-release tag when we push to nuget. Anyone opposed to this?

**Comment by alkampfergit** [comment]
Lets continue discussion on Slack, I've used -buildxxx because the last build from old build server has that numbering. I agree that nuget package should be equal to the FileVErsion. 
Suffix -pre is completely optional, since publishing to nuget is manual process, we can consider pre-release when the package is on myget, and publish on nuget only stable packages.
