### ISSUE TITLE
Move SQL persistence into its own repo

### ISSUE THREAD

**Issue by kblooie** [NEventStore/NEventStore#408]
It's hard to filter issues between NEventStore core API and the SQL implementation. It would be great if SQL was in its own repo. Issues on this repo would be reserved for ideas and changes to the core API.

This will help make it easy to track new features and ideas that affect all the persistence implementations

**Comment by kblooie** [comment]
This would also allow the SQL implementation to be released and versioned separately from the core API, which would make semver easier to follow.

**Comment by kblooie** [comment]
@andreabalducci If you agree, I can get started on this today, before we start on 6.0 development.

**Comment by andreabalducci** [comment]
+1 for a separate repo. Prior to start v6 we need to focus on closing all the issues.
Next release will be 5.3:
- split core & sql persistence
- mongo driver 2.x (.net 4.5)
- raven 3.x (.net 4.5)
- bugfixes

**Comment by kblooie** [comment]
@andreabalducci I'll create the repo now and start copying & referencing the SQL issues to the new repo like we did for the other persistence implementations.

**Comment by kblooie** [comment]
@andreabalducci the new repo's been made & issues transferred. Can you setup the project in TeamCity?

**Comment by andreabalducci** [comment]
@kblooie create the task for @alkampfergit on the sqlpersistence repo
