### ISSUE TITLE
Split out CommonDomain

### ISSUE THREAD

**Issue by kblooie** [NEventStore/NEventStore#410]
I'm not even sure how CommonDomain ended up in the NEventStore assembly. This needs to be a separate package in its own repo.

**Comment by gregoryyoung** [comment]
:+1:

**Comment by andreabalducci** [comment]
don't know, we should ask @damianh.
To be honest we forked common domain and all the devs I know are on their custom common domain so splitting make sense for me. There's a lot of work to do in common domain, could be much faster (even the sql persistence)

**Comment by gregoryyoung** [comment]
Damian IIRC wanted it separate as well the last time I talked though I
don't know his current opinion.

It just doesn't belong with the rest (its like the sesame street game).


The downside of this is a vast portion of people are using common domain
and thus it would be a lower level api offered for people first coming to
the project so it might be worth while to make sure to heavily link to it
so its discovered.

On Sun, May 24, 2015 at 12:22 AM, Andrea Balducci <notifications@github.com>
wrote:

> don't know, we should ask @damianh <https://github.com/damianh>.
> To be honest we forked common domain and all the devs I know are on their
> custom common domain so splitting make sense for me. There's a lot of work
> to do in common domain, could be much faster (even the sql persistence)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NEventStore/NEventStore/issues/410#issuecomment-104945397>
> .
>



-- 
Studying for the Turing test

**Comment by damianh** [comment]
Yes it should be separated out; it was a mistake to include it. It wasn't
being maintained so it was the lazy option. Soz.

**Comment by kblooie** [comment]
I've split this out into its own repo. Just need to setup the build server. @alkampfergit I've added an issue in the repo.
