### ISSUE TITLE
Multiple stores per persistence/storage medium (per database)

### ISSUE THREAD

**Issue by MonkeyJamboree** [NEventStore/NEventStore#413]
Hello. I would like to suggest a new feature: Allowing for multiple event stores per persistence/storage medium. In database terms, multiple Commit and Snapshot tables in a single database.
(Possible resultant feature: Allowing for the Commits and Snapshots table names to be dynamic in nature.)

Use case: multiple (potentially enterprise-scale) systems that use event sourcing and have frequent event writes all connecting to the same persistence/storage medium and all using NEventStore as an event source store. (Examples: Large-scale multi-tenant CRM or Workflow systems; several applications all using the same database for drastically different and unrelated work to keep cloud-based database costs down.)

Use case 2: Other conflicting tables in a database already use the current names for existing, historical data or data for other applications that utilize the same database (I.E. "Commits" in the case of blog posts/comments or "Snapshots" in the case of a photo storage system). Having to move the data to new tables could be an issue for the applications in question, or might be out of the scope of the application utilizing NEventStore

I realize that in the vast majority of cases, this would not be required as stores can save events and snapshots for any number of aggregates. In some edge cases the concrete naming or lack of ability to create multiple stores could potentially be problematic or inflexible.

**Comment by AGiorgetti** [comment]
Maybe I've read this a little too fast and without much in-depth thoughts, but I think you can actually achieve what you are describing using different approaches:
- the 'BucketId' parameter: this way you have a 'discriminator' you can use to segregate different tenants / application / whatever you want on the same EventStore

in the end a 'Database' is just a collection of tables, what you really want to minimize is not the databases per se, but the instances of the engine serving those databases, and this leads to my approach number 2:
- create different databases all server by the same engine instance (ie: 1 sql server instance serving multiple databases)
- configure several instances of NEventStore each one persisting the specific set of data on a different database

Actually the 'snapshotting' is quite custom handled in every project and you can follow whatever strategy you want to deal with the persistence. NEventStore just tracks if an aggregate was snapshotted and which was the version number.

**Comment by MonkeyJamboree** [comment]
Hm. I agree that for most situations those solutions are adequate. I do like the bucketing concept, though I wonder: if the tables get too large due to multiple applications all accessing the same store, how might that affect performance?

In some edge cases though, I would still argue that having the flexibility described would be beneficial. One of which is the case where the decisions are external to development about how databases are created and where data resides (business mandating that several different applications all use the same db, per-db costs on cloud services like Azure, etc). Yes, it's never a good idea to mix data being stored, but it sometimes cannot be avoided. It also might help in cases of DB Admins being particular about what to name tables and the like. Just my feedback on the current state of the product though. :)

I'm pretty new to Event Sourcing in general (and specifically to NEventStore). How could someone persist read models (snapshots) to different snapshot tables in a normalized format?

**Comment by alkampfergit** [comment]
Closed because this should be an option of the provider. As an example, in SqlProvider or MongoDB provider it could be feasible to add a prefix to add to base table / collection.
