### ISSUE TITLE
EnlistInAmbientTransaction should not change isolation level if there is no ambient transaction

### ISSUE THREAD

**Issue by fschmied** [NEventStore/NEventStore#414]
Without `EnlistInAmbientTransaction`, persistence engines are supposed to suppress ambient transactions. For example, [the `SqlPersistenceEngine` uses `TransactionScopeOption.Suppress` around all SQL statements](https://github.com/NEventStore/NEventStore.Persistence.SQL/blob/master/src/NEventStore.Persistence.Sql/SqlPersistenceFactory.cs#L30), causing each database statement issued by NEventStore to be run in a single database transaction with the database default isolation level (SQL Server: `READ COMMITTED`).

When `EnlistInAmbientTransaction` is called in wire-up, the `TransactionScopeOption.Required` is registered instead to be used by persistence engines (via [code in `PersistenceWireup`](https://github.com/NEventStore/NEventStore/blob/master/src/NEventStore/PersistenceWireup.cs#L58)). While this avoids suppressing ambient transaction scopes, it also has the effect of establishing a new default isolation level (if no ambient transaction is present) of `SERIALIZABLE` (the `TransactionScope` default).

For us, this was an unexpected side effect of using `EnlistInAmbientTransaction` - we expected that this changes only the enlisting behavior, not the default isolation level of the persistence engine.

Therefore, I propose changing the behavior of `EnlistInAmbientTransaction` (and the contract with persistence engines) so that it causes _no_ `TransactionScope` to be created _at all_ - neither a suppressing, nor a requiring one. This would keep the default behavior of persistence engines, e.g., that of one `READ COMMITTED` transaction per statement in the SQL Server case.

If this is too heavy a breaking change, I propose adding a new API `EnlistInAmbientTransactionIfAny` with the side effect-free behavior (and maybe deprecating the old one).

**Comment by fschmied** [comment]
It might also be a good idea to move `EnlistInAmbientTransaction` to the _concrete_ persistence wireup, since it doesn't make sense for persistence engines that don't support 2PC (e.g., in-memory, MongoDb (I guess), etc.).

**Comment by fschmied** [comment]
Workaround for 5.2.0: Ensure there is an active `TransactionScope` with `ReadCommitted` isolation level whenever an NEventStore API is called and `EnlistInAmbientTransaction` is turned on.

**Comment by alkampfergit** [comment]
In v6.0 we will move this to SQL persistence provider.

**Comment by AGiorgetti** [comment]
EnlistInAmbientTransaction has been removed from the NEventStore core library, I'm considering removing the creation of "nested" TransactionScope from the Persistence driver too, this ways that can be managed externally without undesired side effects for the clients.

**Comment by fschmied** [comment]
>  I'm considering removing the creation of "nested" TransactionScope from the Persistence driver too, this ways that can be managed externally without undesired side effects for the clients.

@AGiorgetti Just to clarify, this means that enlisting via a surrounding `TransactionScope` still works if the underlying database technology supports this, right?

**Comment by AGiorgetti** [comment]
Yes @fschmied , it should work that way.
