### ISSUE TITLE
Wrong 'using' usage in JsonSerializer class

### ISSUE THREAD

**Issue by AGiorgetti** [NEventStore/NEventStore#417]
I was looking at the code of the JsonSerializer class and I noticed functions like these :

```
protected virtual void Serialize(JsonWriter writer, object graph)
        {
            using (writer)
                GetSerializer(graph.GetType()).Serialize(writer, graph);
        }
```

imo calling using(...) on something that is passed in as a parameter is a mistake, the object will not be guaranteed to be fully initialized anymore and if the caller tries to do something with 'writer' she might get an exception.

**Comment by andreabalducci** [comment]
cannot modify without breaking derived serializers. Current implementation works as expected
