### ISSUE TITLE
ConcurrencyException not thrown as expected

### ISSUE THREAD

**Issue by BennieCopeland** [NEventStore/NEventStore#420]
If you load a stream from in the middle of a commit, and then add new events, a ConcurrencyException is not thrown as expected.

```
IStoreEvents store = Wireup.Init()
    .UsingInMemoryPersistence()
    .InitializeStorageEngine()
    .Build();

using (IEventStream stream = store.OpenStream("1", int.MinValue, 0))
{
    stream.Add(new EventMessage { Body = "1" });
    stream.Add(new EventMessage { Body = "2" });
    stream.Add(new EventMessage { Body = "3" });
    stream.CommitChanges(Guid.NewGuid());

    stream.CommitSequence.Should().Be(1);
    stream.StreamRevision.Should().Be(3);
}

using (IEventStream stream = store.OpenStream("1", int.MinValue, 2))
{
    stream.Add(new EventMessage { Body = "4" });
    stream.Add(new EventMessage { Body = "5" });
    stream.CommitChanges(Guid.NewGuid()); // expected ConcurrencyException
}
```

I believe that the bug is on line 57 of the OptimisticPipelineHook.cs

```
if (head.StreamRevision >= attempt.StreamRevision)
{
    throw new ConcurrencyException();
}
```

should be

```
if (head.StreamRevision >= attempt.StreamRevision - attempt.Events.Count)
{
    throw new ConcurrencyException();
}
```

**Comment by larsw** [comment]
Create/fix test case + code and make a pull request?

**Comment by BennieCopeland** [comment]
I'm working on it now. Making the changes causes `when_committing_with_a_sequence_beyond_the_known_end_of_a_stream` to fail with a `ConcurrencyException` instead of the expected `StorageException` however.

**Comment by BennieCopeland** [comment]
I can fix the test by changing the context to add 2 instead of 1. This makes it appear that there is a missing commit between the stream head and the one being committed. I'm not sure if that matches the original intent of the test or not.

```c#
protected override void Context()
{
    _alreadyCommitted = BuildCommitStub(HeadStreamRevision, HeadCommitSequence);
    _beyondEndOfStream = BuildCommitAttemptStub(HeadStreamRevision + 2, BeyondEndOfStreamCommitSequence);

    Hook.PostCommit(_alreadyCommitted);
}
```

**Comment by andreabalducci** [comment]
Checking in the OptimisticPipelineHooks is not enough, should be handled in OptimisticEventStore on in the PersistenceProviders

**Comment by andreabalducci** [comment]
The real issue is "If you load a stream from in the middle of ~~a~~ **the last** commit, and then add new events, a ConcurrencyException is not thrown as expected."

This should be fixed in OptimisticEventStream, PopulateStream can set a "IsPartialStream" on line 131 and PersistCommit should throw an exception when trying to commit a stream which "is partial".

        private void PopulateStream(int minRevision, int maxRevision, IEnumerable<ICommit> commits)
        {
            foreach (var commit in commits ?? Enumerable.Empty<ICommit>())
            {
                Logger.Verbose(Resources.AddingCommitsToStream, commit.CommitId, commit.Events.Count, StreamId);
                _identifiers.Add(commit.CommitId);

                CommitSequence = commit.CommitSequence;
                int currentRevision = commit.StreamRevision - commit.Events.Count + 1;
                if (currentRevision > maxRevision)
                {
                    IsPartialStream = true;  // <----------------------------------------------
                    return;
                }

                CopyToCommittedHeaders(commit);
                CopyToEvents(minRevision, maxRevision, currentRevision, commit);
            }
        }

The case of a partialstream from an incomplete sequence of commits (your version match with the last version of a commit but the commit is not the last one) is already handled by the persistence provider with an unique index on the CommitSequence.
