### ISSUE TITLE
PollingClient doesn't use exception handler passed when subscribing

### ISSUE THREAD

**Issue by yurapara** [NEventStore/NEventStore#423]
When [Subscribe] (https://github.com/NEventStore/NEventStore/blob/master/src/NEventStore/Client/PollingClient.cs#L70) to PollingObserveCommits it's possible to pass OnError action for exception handling. But it doesn't look to be used there, or?
In case of exception when [reading commits](https://github.com/NEventStore/NEventStore/blob/master/src/NEventStore/Client/PollingClient.cs#L122) or when [handling them] (https://github.com/NEventStore/NEventStore/blob/master/src/NEventStore/Client/PollingClient.cs#L133) it's [only written to log] (https://github.com/NEventStore/NEventStore/blob/master/src/NEventStore/Client/PollingClient.cs#L140). Shouldn't `_subject.OnError(ex);` be called there also?

**Comment by andreabalducci** [comment]
Calling OnError would stop the client:

> Rx has an implicit contract that must be followed. An implementation of IObserver<T> may have zero or more calls to OnNext(T) followed optionally by a call to either OnError(Exception) or OnCompleted(). This protocol ensures that if a sequence terminates, it is always terminated by an OnError(Exception), or an OnCompleted()

http://www.introtorx.com/Content/v1.0.10621.0/02_KeyTypes.html#IObserver
