### ISSUE TITLE
Isolation level bug in SQL Server

### ISSUE THREAD

**Issue by chrischu** [NEventStore/NEventStore#424]
Unfortunately SQL Server has a bug with transaction isolation levels that could lead to invalid isolation levels being used. When getting a connection from the connection pool, the isolation level is not reset to the default (ReadCommitted) so isolation levels from previous connections can leak into new connections.

I created a rempro sample that showcases the problem (see attached files):
[NEventStoreIsolationLevelReproSample.zip](https://github.com/NEventStore/NEventStore/files/169125/NEventStoreIsolationLevelReproSample.zip)

**Comment by chrischu** [comment]
My proposed solution is to explicitly set the isolation level to the default after opening a connection. For this purpose ISqlDialect probably needs a new method that is invoked after the connection is opened, the MSqlDialect can then set the isolation level explicitly in that method.

I'll probably start working on a pull request for this idea next week (Monday). If someone has comments/other suggestions it would be cool if they could be posted over the weekend so I can take them into account :).

**Comment by andreabalducci** [comment]
discussion moved to Sql Persistence Repository
