### ISSUE TITLE
Update Reactive Extensions to the latest stable build (2.2.5)

### ISSUE THREAD

**Issue by AGiorgetti** [NEventStore/NEventStore#429]

**Comment by alkampfergit** [comment]
I think it can be done, but probably it will be a better solution to avoid dependencies from reactive in the new version (move polling client in another separated project published under a different nuget package maybe?)

**Comment by AGiorgetti** [comment]
or... Is it better to remove it completely to not hit another external dependency?

**Comment by alkampfergit** [comment]
RX reference will be removed
