### ISSUE TITLE
.NET Core/CoreCLR Port?

### ISSUE THREAD

**Issue by TsengSR** [NEventStore/NEventStore#430]
As the ASP.NET Core RC2 is about to hit it's release (scheduled for mid May 2016 and RTM for end of June), what is the state/plans of NEventStore towards it? 

No question is a huge gain to be able to natively write .NET/C# code on Linux w/o dependency on the full fledged .NET Framework which only runs on Windows but also on the new minimalized Windows Nano Server where the full .NET framework is not supported.

**Comment by jjrdk** [comment]
I have run NEventStore under Mono without problems, so I'm not sure that there is a huge benefit in looking at ASP.NET Core at the moment.

**Comment by MetaFight** [comment]
Mono and .net core are two very different targets.

**Comment by jjrdk** [comment]
The point I was trying to make was that netcore targets mainly websites and not really server applications. Since the current release runs fine on mono there is little benefit in doing a port. Also consider that netcore is still quite unstable, so there will be a lot of friction.

**Comment by MetaFight** [comment]
I'm not sure I understand your "server application"/"website" distinction.  But, I agree .net core is still a bit rough around the edges.

**Comment by TsengSR** [comment]
> The point I was trying to make was that netcore targets mainly websites and not really server applications. 

That's complete nonsense. Are you mixing ASP.NET Core with .NET Core? .NET Core is the (portable) runtime, ASP.NET Core is just a webstack (which runs on either full .NET Framework or .NET Core). 

And .NET Core is suitable for server applications as you can also create console applications (w/o ASP.NET Core) with it. And with .NET Standard 2.0 (which introduces much more new APIs to .NET Core) a migration ist even more required as by then there would be even less reasons to use mono. 

Mono is just broken and slow. All our new Projects target either full .NET Framework (4.6.x) or .NET Core if portability/platform independence is important (i.e. docker support).

**Comment by alkampfergit** [comment]
Once .NET standard 2.0 will be out, it will be time to make neventstore compatible with it, I agree.

**Comment by QJonny** [comment]
Hi, first of all thank you for your great job!
Do you have any updates about the possible release dates of the version supporting netstandard?
Especially that now the netcore 2.0 preview is out there

Thank you!!!

**Comment by QJonny** [comment]
Ping

**Comment by andreabalducci** [comment]
I'm working on a full async, netstandard rewrite (https://github.com/ProximoSrl/NStore) to evaluate the new api. 

**Could** become the new version of NEventStore with a cleaner API and a migration tool. Next Milestone will add RDBMS support.

Actual codebase needs a full cleanup and I'm not sure it's worth the cost to carry on lot of **old** (and probably unused) stuff from the past.

**Comment by AGiorgetti** [comment]
I was working on the porting on a feature branch, it did compile and run most of the correctly with .NET Core 1.1, there were some tests that needs some love with the MongoDB provider, none of the other storage were ported in that branch.

I also had to change the testing framework from xunit to the new MSTest v2.

I need to rework it again for the .NET Core 2.x and the new  netstandard, but maybe @andreabalducci work will take over, we still need to check it.

In the meanwhile look at the feature/dotnetcore branch.

**Comment by QJonny** [comment]
Thank you for your answers.
Actually I looked at the feature/dotnetcore branch and I can build it against netcore. 
The only problem is that I need sqlite persistence. I tried to build the project, but sadly it needs some netcore 2.0 api, so I think this would be available only after the netcore 2.0 adaptation.  

Ok I'll wait :) 
Thank you for your work!!

**Comment by Lanayx** [comment]
I've tried to build feature/dotnetcore and reference it from .net core 1.1 project. Build was fine, but when running with _dotnet run_, got this error.

```
Unhandled Exception: System.TypeInitializationException: The type initializer for '<StartupCode$ProblemService>.$ProblemService.App' threw an exception. --
-> System.IO.FileNotFoundException: Could not load file or assembly 'NEventStore.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. 
   at EventStore.inMemoryEventStore()
   at <StartupCode$ProblemService>.$ProblemService.App..cctor()
   --- End of inner exception stack trace ---
   at ProblemService.App.main(String[] argv)
```

**Comment by AGiorgetti** [comment]
The porting is slowly moving on, we've decided to change the target to NetStandard 2.0 (.net core 2.0). the  verious 'feature/dotnetcore' branches have been updated.
You can check:
NEventStore, NEventStore.Domain, NEventStore.Persistence.MongoDB, NEventStore.Persistence.Sql (only SqlLite and MsSqlServer have been tested so far)

**Comment by oinant** [comment]
Hello,
I'm eager to help migrating the project to netcore2.0. 
Is there a roadmap or else which can help me to start?

**Comment by AGiorgetti** [comment]
Hi @oinant, check the 'feature/dotnetcore' branch, it has a complete port to netstandard2.0

the solution is named: NEventStore.Core.sln

**Comment by oinant** [comment]
Yes, i saw it. Is there any plan to merge it into the master branch, so it could be released within the nuget packages?

**Comment by psandler** [comment]
+1 to SonOfPirate's question.  Is the branch considered stable, or will it be merged in?  Seems there was a commit as recently as yesterday.

**Comment by AGiorgetti** [comment]
The branch is stable enough (all the tests are green), it has the same code of the "develop" branch which I have currently in production since years.
The .net core branches have multitarget support for "net45" and "netstarndard2.0".
The working providers are for MongoDB, Sql Lite and MsSqlServer, have to test other sql databases, but they should work.
I'm working on setting up the build and test server again so we can merge it and publish the packages.

**Comment by pcoombe** [comment]
> I'm working on setting up the build and test server again so we can merge it and publish the packages.

i know its a how long is a piece of string question, but do you have an expected time frame for this?
we were only talking in my team yesterday about ripping neventstore out of our project, but this might extend its life a bit longer, at least until we get past some deadlines.

**Comment by andreabalducci** [comment]
@pcoombe TBH we moved almost all of our products to NStore, we spent some time in a full rewrite in .netstandard + async NEventstore like library much simpler, memory friendly and more extensible.
We still have some service on top of NES, so we are maintaining the repo.

Sadly we are a small team, in a huge project with a tight schedule, it's hard to find the time to keep all up to date.

If you and your team can find some time to setup a CI build on appveryor and send a PR we could publish netstandard support in few days.

You can find some sample here https://github.com/ProximoSrl/NStore/blob/develop/appveyor.yml 
Thank you for your support.

**Comment by AGiorgetti** [comment]
I've just added a first version of an AppVeyor script to the dotnetcore branch, it can be used as a starting point for all the projects

**Comment by Wesam18** [comment]
@AGiorgetti  any plan for releasing dontet core branch?

I tried 5.2 with dotnet core, and it give me a lot of problems, it there are workaround until you release the dotnotcore branch?

**Comment by leewalkergm** [comment]
@AGiorgetti What's the status of this? I've seen that the dotnet standard branch has passing builds on Appveyor

Is there anything that I can do to help get the dotnet core/standard branch released?

**Comment by AGiorgetti** [comment]
@leewalkergm The branch is fully functional and can be used, I just need a review by the rest of the Team to merge it in develop and release the V6 version with full framework and dotnet standard 2 support.

In the meanwhile you can clone and build the "feature/dotnetcore" branches yourself, there are build script in every project.

**Comment by leewalkergm** [comment]
Fantastic news, thanks for the swift response!

**Comment by esbenbach** [comment]
Any progress on getting it approved by "the team"?

**Comment by threezool** [comment]
Any update?

**Comment by AGiorgetti** [comment]
I've fixed the NuGet packages generation (which I broke in the migration process), hope to release an "rc.0" soon

**Comment by AGiorgetti** [comment]
Branch merged with master, NuGet packages will be available soon.
