### ISSUE TITLE
Build.RunTask.bat fails because NuGet packages do not exist

### ISSUE THREAD

**Issue by TimMurphy** [NEventStore/NEventStore#431]
Very easy to reproduce:

- Clone repository
- Run Build.RunTask.bat
- First of many similar errors `C:\Users\tim\Code\OpenSource\NEventStore\src\.nuget\nuget.targets(92,9): error : Unable to find version '6.0.1' of pack
age 'Newtonsoft.Json'. [C:\Users\tim\Code\OpenSource\NEventStore\src\NEventStore\NEventStore.csproj]`

## Workaround

Build solution with Visual Studio first.

**Comment by alkampfergit** [comment]
@TimMurphy I think that there is a problem in your configuration with Nuget. Actually I've done a fresh clone of NeventStore and both master and develop branch can compile with Build.RunTask.bat without problem.

**Comment by TimMurphy** [comment]
Well I'm stumped.

Started the morning to resolve the issue.


   - Tested still an issue on my machine. It was.
   - Did some fiddling to get it to work and did.
   - Reset everything to prove it wasn't working before creating a pull
   request.
   - Now it works without any changes.

I give up :-( Close the issue.



On Thu, Jun 16, 2016 at 6:38 PM, Gian Maria <notifications@github.com>
wrote:

> @TimMurphy <https://github.com/TimMurphy> I think that there is a problem
> in your configuration with Nuget. Actually I've done a fresh clone of
> NeventStore and both master and develop branch can compile with
> Build.RunTask.bat without problem.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NEventStore/NEventStore/issues/431#issuecomment-226423123>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAZRju6N9A0tPoibfiPjKsyf7lFNp2wkks5qMQtogaJpZM4IyWYY>
> .
>



-- 
Tim Murphy

Need a website and/or blog that's easy to create and update? Check out
Impressive
Mark <http://impressivemark.com/>.
