### ISSUE TITLE
Reading CommitedEvents into Objects

### ISSUE THREAD

**Issue by btrepp** [NEventStore/NEventStore#433]
I'm trying to read all the events back out of the event store into objects, so I can use them.

I have

```
public IEnumerable<Event> Get(Guid AggregateId, int Version)
        {
            using (var stream=_store.OpenStream(AggregateId, 0,Version))
            {
                return stream.CommittedEvents.Select(ToDomainEvent);
            }
        }
public Event ToDomainEvent(EventMessage arg)
       {
            return ????;
       }
```

Wired up with
```
var conn = iocontainer.Resolve<ConnectionString>();
            return Wireup.Init()
                          .UsingSqlPersistence("Default", conn.Provider, conn.Value)
                          .WithDialect(new MsSqlDialect())
                          .InitializeStorageEngine()
                          .UsingJsonSerialization()
                          .Build();
```

The issue is that EventMessage.Body returns a JObject class that is the internalized one. I can't seem to do anything with this object. I can't reference the internalized namespace, so I can't cast it to that. 
Attempting to cast it to the JSON.Net i have installed (9) results in errors at runtime.

It appears this is the same object in the ICommit on a polling client.

The event class is from F#.

What is the proper way of reading event data back from the store?. When I was using the memory persistence engine a cast worked, but it seems the serialized/deserializer doesn't produce the same objects that went in?.

I am using NEventStore 5.2.0 from Nuget.

**Comment by btrepp** [comment]
Okay I'd say this is somesorta bug in the serialization. Though I don't know where to look to fix it.

The workaround I have is using https://github.com/NEventStore/NEventStore.CustomJsonSerializerSample
as the serializer.

Then dealing with the `JObjects` are now using my projects version of JSON.Net. So I convert them to actual objects using

```
var events = commit.Events.Select(n=>n.Body).Cast<JObject>().Select(x=>x.ToObject<Domain.Application.Event>());
```

Somewhere along the line the serializer seems to just be punting and not deserializing into the type. I geuss this makes sense, it has no idea what the type would be. Is there a way of telling the serializer to embed the type information so it knows how to deserialize it?.

I'm also confused as to why the inmemory store doesn't have this problem?. I would assume it uses the serializer but stores it in memory, but maybe its just storing the objects instead of serializing/deserializing them?

**Comment by alkampfergit** [comment]
Have you tried to serialize deserialize manually your event class with Json outside of NEventStore? Could you please provide a small project that reproduces the issue to understand what is going on? 

Thanks.

**Comment by btrepp** [comment]
I've created a small project here. It serializes using json for both the inmemory and SQL store.

I've added methods that simply cast the message body into the type it was when it was serialized. The inmemory store works fine, the SQL store throws an exception because it has deserialized the object as a JObject.

https://github.com/btrepp/NEventStoreSerializationIssue

The payload stored in the commit table of the database when converted from binary to Ascii is.
` [{"Headers":{},"Body":{"Case":"EventTypeNumber1","Fields":["TEST"]}}]`

What I believe is happening is it is not including the Type information in the serialization, so when it comes to deserialization, it "falls back" to JObject. 

It also appears that InMemoryPersistence doesn't care/use serialization methods, thats okay but it would be great if there was an InMemoryPersistence provider that serialized data the same as other stores, that way I can swap them out easily.

**Comment by alkampfergit** [comment]
The problem happens with F# classes, probably with current serialization option Json.NET does not include serialization information. If I try with a class written in C# here is the output I got

I've modified your example to save another commit with a payload containing a class written in C# and here is the output

```
Dumping Memory Store
Event type Library1.Event ToString Library1.Event
Event type Library2.Test ToString Library2.Test

Dumping Sql Store
Event type Newtonsoft.Json.Linq.JObject ToString {
  "Case": "EventTypeNumber1",
  "Fields": [
    "TEST"
  ]
}
Event type Library2.Test ToString Library2.Test
```

that clearly shows me that while the C# class is deserialized correctly, the F# one is not. You should probably use [Custom serializer](https://github.com/NEventStore/NEventStore.CustomJsonSerializerSample) and investigate in all Json.NEt option to force serialize type information for F# types.

**Comment by alkampfergit** [comment]
It seems a problem of Json.Net serializer, if you create a simple wrapper class

```
   public class Wrapper
    {
        public Library1.Event evt { get; set; }
    }
```

and store this class inside an EventMessage, it will be deserialized correctly and the inner evt property is correct.

**Comment by btrepp** [comment]
That's an acceptable workaround for me :). It works with a F# class too, which is basically the C# class written in F#.
```
type wrapper<'a>()= 
        member val Event:'a option=None with get,set
```

I have used Json.Net to deserilize F# discriminated unions before, but thats using the DesierliazeObject<T> so thats how JSON.Net was getting the type info.

**Comment by alkampfergit** [comment]
If you think that using wrapper is a good workaround for F# discriminated unions you can close the issue. You can also use a custom serializer that uses DeserializeObjec or other json serializer than Json.Net if you like, but I think that a wrapper is the simplest solution.

Thanks.
