### ISSUE TITLE
StreamNotFound Exception is vague in use case of non-existent commit id

### ISSUE THREAD

**Issue by bigjonroberts** [NEventStore/NEventStore#439]
In this particular case I wanted to give a rest client a view of events as a type of audit log for an aggregate.  We may implement dispatching via websockets at some point in the future, but for now we are polling from the client.  When polling we are calling `IEventStream.OpenStream()`.  If we are polling for new events beyond what we have received already, we set a value at `CommitSequence + 1`.

This situation was reported previously over two years ago in the NEventStore Google Group here:
https://groups.google.com/forum/#!topic/neventstore/hsK5Q3Ath-Y  

Mr. Gonzalez raised his query in regard to snapshots, but this is a very similar situation with the same result.

I'm very new to NEventStore and to Event Sourcing in general.  I attempted to search this repo, issues, documentation, and StackOverflow prior to posting this issue.  Hopefully I have not raised an issue that already has a solution elsewhere.

I have a workaround for now, but this does not seem to be the best behavior as a stream does indeed exist, but doesn't have a commit sequence existing at the requested mincommit.

**Comment by alkampfergit** [comment]
I think that probably raising a better exception is the correct solution, to inform the caller that the stream exists, but you asked for a revision that does not exists.

In your specific situation I think that PollingClient class would be the best solution.
