### ISSUE TITLE
Direction & Roadmap

### ISSUE THREAD

**Issue by DamianReeves** [NEventStore/NEventStore#451]
I keep coming back to NEventStore and I keep wondering if this is something I should use in a green-field project.

The lack of clear direction and a roadmap (at least from the outside looking in), makes me hesitant, despite the maturity of the project. 

Is it the case that this is mature and just works, or have people adopted alternate solutions (i.e. https://geteventstore.com/)?

I see work progressing in the develop branch but there has been no release (not even a pre-release) in a year and a half.

Can you help me understand the direction of this project?
Also in keeping in modern times, it might be useful to setup a gitter chat room for the project.

**Comment by corfor** [comment]
You are right to be hesitant. I just used it on a greenfield project, and it is not without significant complications. If I knew then what I know now, I would pick something else.

There is a channel on Slack for discussing NEventStore with the smart guys in the room.
https://ddd-cqrs-es.slack.com/archives/neventstore

**Comment by DamianReeves** [comment]
How do I get access to that channel?

**Comment by DamianReeves** [comment]
Nevermind. I'm in.

**Comment by vorosoft** [comment]
@corfor What would you pick?

**Comment by corfor** [comment]
I would take a serious look at Akka.NET and its persistence.
http://getakka.net/docs/#akka-persistence

**Comment by mcquiggd** [comment]
@corfor 

If you have time, could you briefly give us a heads up about issues you have encountered..? Areas where we may encounter difficulties?

Regards,

David

**Comment by mcquiggd** [comment]
@DamianReeves 

Could you share with us how you gained access to the Slack channel? I am presuming it is invitation only?

David

**Comment by damianh** [comment]
@mcquiggd Get an auto-invite here https://ddd-cqrs-es.herokuapp.com/

**Comment by mcquiggd** [comment]
@damianh 

Many thanks... lots to catch up on there :)

**Comment by andreabalducci** [comment]
We use NES heavily in our products (on mongodb) using the develop branch and myget packages.
We have not had the time to review all the persistence providers to release on Nuget all the stuff, it's something we want to do when we can (doesn't pay our bills).

the direction is:
1) api cleanup
2) simplify stuff (snapshots, caches, etc)
3) move to netcore 2.x (thre's already an experimental port on netcore 1.x)
4) samples & docs

0) find more time to work on nes.
