### ISSUE TITLE
Supporting Multiple IDs (PrimaryKey & AltKeys) Cross References

### ISSUE THREAD

**Issue by DR9885** [NEventStore/NEventStore#453]
I have Multiple data sources coming in. Each of these sources give me data about an Single Entity. This entity has multiple Id's. Not all ID's are always available, and different sources use different ID's but I'm able to bridge the gap.

Given any of these IDs I would need to load or save events to the one stream. No matter the ID. There are merge cases, that I plan to manually fix, but I'm more uncertain with how I can do this useing NEventStore. I've thought about using a second storage for references from key to sourceId, but I was hoping a suggestion could be made as I'm sure this is a common problem.

Example:
Source1: ID1, ID2
Source2: ID1
Source3: ID2

or Merge Case

Source1: ID1
Source2: ID2
Source3: ID1, ID2

**Comment by fschmied** [comment]
Could you combine the two Ids into a single compound key for your streams?

----- Ursprüngliche Nachricht -----
Von: "Daniel P. Rossi" <notifications@github.com>
Gesendet: ‎04.‎02.‎2017 00:39
An: "NEventStore/NEventStore" <NEventStore@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: [NEventStore/NEventStore] Supporting Multiple IDs (PrimaryKey &AltKeys) Cross References (#453)

Lets say I have two or more Ids, for example "ID1", "ID2". and lets say sometimes I receive one, sometimes the other, and in rare cases I receive both. Is there anyway I could do this with NEventStore? The only way I can think of it is storing multiple streams, but that seems like a bad idea.

**Comment by DR9885** [comment]
That wouldn't work because not all sources return both keys. Sometimes I get one or the other, and in rare cases I get both.

**Comment by fschmied** [comment]
You mean the same logical "entity" (aggregate, etc.) has to be identifiable
via either key at the same time?

Could you define one key to be the "main" key? If so, use this for
identifying the stream in NEventStore, and build a projection/read model
mapping the secondary key to the main key. Then, when you receive the
secondary key, you look up the main one, and use that for accessing the
event stream.

**Comment by DR9885** [comment]
No single key is always available... I think I'll just have to use the primary key of the read model... but I was hoping I could store the events before attempting to get the read model. Just to ensure every event is saved even if the read model is having issues.
