### ISSUE TITLE
I'd like to see new Persistence engine for Elasticsearch

### ISSUE THREAD

**Issue by risogolo** [NEventStore/NEventStore#457]

**Comment by maxcherednik** [comment]
Good idea! Pull requests are welcome here!

**Comment by alkampfergit** [comment]
I think that this is not a really good idea. ElasticSearch is not really suitable for primary store, it has not unique indexes, it is eventually consistent (you insert and you need to wait time for the document to show up in search)

I'm curious why using elasticsearch over MongoDb, or Sql Server. If your need is using the searching capability of ES, the best solution is creating a projection that scan your NES primary database and index data for searching IMHO.

**Comment by risogolo** [comment]
The reason is simple, we want to avoid introducing additional DB engine on our project, either relational or document

**Comment by andreabalducci** [comment]
Elastic is not suitable for primary persistence and misses some features (es: unique indexes).
not the right tool for a reliable eventstore-
