### ISSUE TITLE
Please strongly name the assembly

### ISSUE THREAD

**Issue by ludydoo** [NEventStore/NEventStore#460]
Hi,

This is just a minor annoyance, but could you strongly name the assembly? I get lots of warning in VS2017 because of that.

Thank you

**Comment by zplan** [comment]
Yes, we need this as well. But for us it is not minor :)

Thx

**Comment by tlycken** [comment]
I have no affiliation with NEventStore, but since it's even in the wiki that this will never happen, I don't think you should get your hopes up: https://github.com/NEventStore/NEventStore/wiki/Statement-on-strong-naming

**Comment by fschmied** [comment]
Note that Damian, who wrote that statement in the wiki, is no longer maintaining this project. Also, the position of the NuGet team on strong naming seems to have changed; e.g., auto-signing was never implemented. Maybe @alkampfergit and @andreabalducci can be convinced to accept a pull request? :)

Here is an old mailing list thread with some discussion: "https://groups.google.com/d/msg/neventstore/zJt0g4NhieM/_275CbgXZk4J".

**Comment by andreabalducci** [comment]
Strong naming has issues for OSS projects, NES will not be signed.
