### ISSUE TITLE
What is deprecated: UsingAsynchronousDispatchScheduler, UsingSynchronousDispatchScheduler or both? 

### ISSUE THREAD

**Issue by MNF** [NEventStore/NEventStore#461]
In QuickStart https://github.com/NEventStore/NEventStore/wiki/Quick-Start there is an unclear paragraph 

> UsingSynchronousDispatchScheduler(), DispatchTo(new DelegateMessageDispatcher(DispatchCommit))
> 
> Configures how events will be "dispatched" to "the event bus". Alternative is "UsingAsynchronousDispatchScheduler". This is deprecated and should no longer be used because ...
> Use PollingClient instead, which solves these issues.
> 

What is deprecated: UsingAsynchronousDispatchScheduler, UsingSynchronousDispatchScheduler or both? 
Please clarify wiki.
Also link to PollingClient example will be good.

**Comment by AGiorgetti** [comment]
Hi, the whole dispatching mechanism has been deprecated and removed from the develop branch.
You can implement your own dispatching using a pipeline hook, if you want.

A sample for the PollingClient can be found in this project: 
https://github.com/NEventStore/NEventStore/tree/develop/src/NEventStore.PollingClientExample

**Comment by kirodge** [comment]
Thanks for clarifying here, but the wiki's Quick start guide is still confusing. 
The example at the top contains UsingAsynchronousDispatchScheduler:
> var store = Wireup.Init()
...
.UsingAsynchronousDispatchScheduler()
// Example of NServiceBus dispatcher: https://gist.github.com/1311195
.DispatchTo(new My_NServiceBus_Or_MassTransit_OrEven_WCF_Adapter_Code())
.Build();	

And when I want to know what that is for, I read at the bottom of the page:
>Alternative is "UsingAsynchronousDispatchScheduler". This is deprecated

Please update the wiki.

**Comment by dennisdoomen** [comment]
Or use something like https://github.com/liquidprojections/LiquidProjections.NEventstore

**Comment by AGiorgetti** [comment]
Closing this Issue and opening a new one on updating the WIKI (#471)
