### ISSUE TITLE
NEventStore.ConcurrencyException when calling CommitChanges twice for the same StreamId

### ISSUE THREAD

**Issue by cezarypiatek** [NEventStore/NEventStore#462]
Hi

I'm getting unexpected NEventStore.ConcurrencyException when I call CommitChanges method twice for the same streamId. Here is my method which I use to persist my events (Invoking this method twice results with ConcurencyException)

```cs
public void Store(string streamId, string eventType, IEvent @event)
{
	using (var stream = this.connection.CreateStream(streamId))
	{
		var message = new EventMessage
		{
			Body = @event,
			Headers =
			{
				["Type"] = eventType,
				["CreatedOn"] = DateTime.Now
			}
		};
		stream.Add(message);
		var commitId = Guid.NewGuid();
		stream.CommitChanges(commitId);
	}
}
```

I'm using InMemoryPersistance with the following boostraping code

```cs
public override void Init()
{

	this.connection = Wireup.Init()
							.UsingInMemoryPersistence()
							.InitializeStorageEngine()
							.UsingJsonSerialization()
							.Compress()
							.Build();	
   
}
```

Is this by design and I'm doing something wrong or InMemoryPersistance is not working correctly?

**Comment by fschmied** [comment]
You're using `CreateStream`. When calling that twice with the same streamId, the second call will throw a `ConcurrencyException` because the stream already exists.

Use `OpenStream` instead.

**Comment by cezarypiatek** [comment]
OpenStream solved my problem. Thanks for your help @fschmied
