### ISSUE TITLE
Project current status

### ISSUE THREAD

**Issue by NevRA** [NEventStore/NEventStore#464]
Does this project alive? I don't see any new commits for few last months.
Thanks

**Comment by alkampfergit** [comment]
Actually it is quite stalled.

You can Check nstore https://github.com/ProximoSrl/NStore

Il 22 feb 2018 22:29, "Roman Abdulmanov" <notifications@github.com> ha
scritto:

**Comment by sapiens** [comment]
You can give [DominoES](https://github.com/sapiens/DominoEventStore) a try as well (disclaimer: I'm the author). It's .net standard 1.6 and it has some features unavailable in NEventStore (the reason why I've started the project in the first place)

**Comment by damianh** [comment]
Adding [SQLStreamStore](https://github.com/SqlStreamStore/) to the list to check out. [The reasons why I started it](https://github.com/SQLStreamStore/SQLStreamStore/issues/108).
