### ISSUE TITLE
dotnetcore 2.1/2.2/2.x

### ISSUE THREAD

**Issue by stevematyas** [NEventStore/NEventStore#476]
I see from the documentation that 2.0 is supported. What's more, I saw that the `develop` branch seems to have some 2.x support though it's unclear. Could someone provide an details on what may or may not work for 2.1, 2.2 or 2.x?

**Comment by AGiorgetti** [comment]
Hi, the minimum netstandard supported version is 2.0, so you should be able to use it with any dotnet core 2.x.

**Comment by stevematyas** [comment]
Thank you. We'll be sure to file any issues we uncover with our usage of dotnetcore 2.1
