### ISSUE TITLE
Paging over all events

### ISSUE THREAD

**Issue by RyanBuzzInteractive** [NEventStore/NEventStore#481]
This is probably a stupid question, apologies in advance.

If I want to iterate over all of the events in a given partition, it looks like I should call:

`var allCommits = eventStore.Advanced.GetFrom(bucketId, checkpoint)`
 
I can see that the method returns an IEnumerable of all the commits after the checkpoint.

If I use Linq  `allCommits.Take(someNumber)` to trim the sequence length, will that prevent the rest of the items being loaded into memory? 

Obviously there could be many commits, so  I am looking for a way to page over them essentially. 

I guess I should also call ToList() before returning the IEnumerable from my repository in order to execute the query?

I am only really familiar with SQLite + LinqToSql which is why I am guessing it works this way, but I know NES is persistance agnostic so I understand it may be very different.

Cheers,
Ryan

**Comment by AGiorgetti** [comment]
Every driver has its own specific implementation, but all of them will internally use a cursor to iterate over the collection or some sort of pagination.

You can attach a profiler to your database and confirm the records are read in blocks (if it's not the case, report the bug please).

However in version 7.0.0 we've just added two more overloads of the IPersistStream.GetFromTo() method that will allow you to specify the lower (excluded) and upper (included) checkpoint bounds of the commits to retrieve.

**Comment by AGiorgetti** [comment]
Closed by mistake

**Comment by RyanBuzzInteractive** [comment]
> However in version 7.0.0 we've just added two more overloads of the IPersistStream.GetFromTo() method that will allow you to specify the lower (excluded) and upper (included) checkpoint bounds of the commits to retrieve.

This is great news, just what I was after, thanks!

**Comment by AGiorgetti** [comment]
good! i can close the issue then.
