### ISSUE TITLE
Iterating over all streams

### ISSUE THREAD

**Issue by RyanBuzzInteractive** [NEventStore/NEventStore#482]
Is there any way of saying 'foreach stream in allStreams'?

My application has a server and a mobile client, and I am saving the mobile's offline-generated commands so that they can be merged by re-executing against newly-pulled server data when back online.

I would like to do this stream-wise so that I only have to load up each existing aggregate once during the merge.

**Comment by RyanBuzzInteractive** [comment]
If there isn't already a way to directly acheive the above, would

`eventStore.Advanced.GetFrom(0).Select(commit => commit.StreamId).Distinct().ToList()`

be an efficient way of getting all stream IDs so that I can load up each in turn?

i.e., would that prevent all of the commits being loaded into memory at once?

**Comment by AGiorgetti** [comment]
It's not efficient nor a recommended practice to use the API like that. 

IPersistStreams was originally designed to write to and read from the persisted storage.

If you want to do that kind of queries it's better to write them directly against the underlying database.

Another alternative is to create a dedicated projection of the data that suits your needs and query over that one.
