### ISSUE TITLE
Changelog clarification: Serialization/Data format changes between 5.2.0 and newer

### ISSUE THREAD

**Issue by esbenbach** [NEventStore/NEventStore#485]
Hi - first of all, thanks for the work being done on this project!

We are currently on 5.2.0 (last full framework version afaik).
We are in the process of migrating to a newer version of NEventStore - while reading the changelog regarding breaking changes the main thing mentioned are code incompatibilities. 
While those are great to highlight and we need to solve them, I am way more concerned with data incompatibilities, and there are no mentions of this in the changelog.

Could you clarify if the data i have stored using 5.2.0 is will still be accessible using 6.x - or will we have to migrate the data as well?

Ideally put the information in the changelog together with the information about breaking changes :)

**Comment by esbenbach** [comment]
For anyone who may be interested, i did some tests and found that there are no breaking changes in the payload. 
For my tests I have used compression but NOT encryption, so I can't speak for the encryption algorithm.

**Comment by AGiorgetti** [comment]
I am not aware of any breaking changes that impacted how the data was serialized, all the known breaking changes were listed in the changelog.
If you find something that we missed, let us know it and we'll update the changelog (or provide a PR for that).

Thanks!

**Comment by esbenbach** [comment]
Seems there arent any, so unless you want it as a clarification you can just close this issue.
