### ISSUE TITLE
Upgrading from NES5 to NES8 - what happened to commit dispatchers?

### ISSUE THREAD

**Issue by drauch** [NEventStore/NEventStore#490]
Hi!

We're using commit dispatchers to build a synchronous read model which should be consistent with the event store. We've used commit dispatchers for that purpose in NES5. Now we want to migrate to .NET Core and thereby to NES8 - what is the successor of commit dispatchers? Are they maybe still available? It looks like they've been removed in https://github.com/NEventStore/NEventStore/commit/e98a9c6539391982cec90a56eb619550975c792e

Best regards,
D.R.

**Comment by AGiorgetti** [comment]
HI, dispatchers were deprecated in version 5.x and removed since version 6.0.0. Take a look at the changelog for more details.
